parameters:
#    esiee_game.example.class: ESIEE\GameBundle\Example

services:
    sonata.admin.ground:
        class: ESIEE\GameBundle\Admin\GroundAdmin
        arguments:
            - ~
            - ESIEE\GameBundle\Entity\Ground
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Elements de jeu", label: Terrains }
