parameters:
#    esiee_user.example.class: ESIEE\UserBundle\Example

services:
#    esiee_user.example:
#        class: %esiee_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
